# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21449f693dd4b49f792d58d50d74e1915e22761d4ae907dbefd9821a6109ea400d95bbe8ca2a14262fdf0d468dda4b289cab7308aeefe1761ba701802e4dba79

test:
  secret_key_base: 9041d248c01029d0582bf48f2c32691148f4232ad60e35a720add29cbaefc52f5f262b9dfb87725cb4e9501fd76af9717a750c5f73210882abc8e4a6d1716888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
